# Get your credentials by signing up here: https://api.igdb.com/admin and put them in your .env file
en_igdb_api:
    base_url: 'http://cors.io/?https://api-2445582011268.apicast.io'
    api_key: 'f52352e7365211a1674dda4f6e8b01ce'
